struct GodvilleHero: Decodable {
    let words: Int?
    let boss_name: String?
    let boss_power: Int?
    let activatables: [String]?
    let ark_f: Int?
    let ark_m: Int?
    let savings: String?
    let t_level: Int?
    let arena_won: Int?
    let arena_lost: Int?
    let arena_fight: Bool?
    let ark_completed_at: String?
    let alignment: String?
    let aura: String?
    let bricks_cnt: Int?
    let clan: String?
    let clan_position: String?
    let diary_last: String?
    let distance: Int?
    let exp_progress: Int?
    let expired: Bool?
    let fight_type: String?
    let godpower: Int?
    let gold_approx: String?
    let gender: String?
    let godname: String?
    let health: Int?
    let inventory_max_num: Int?
    let inventory_num: Int?
    let level: Int?
    let max_health: Int?
    let motto: String?
    let name: String?
    let pet: Pet?
    let quest_progress: Int?
    let quest: String?
    let savings_completed_at: String?
    let shop_name: String?
    let temple_completed_at: String?
    let town_name: String?
    let wood_cnt: Int?
}
